### ISSUE TITLE
torrent_server.py error!!

### ISSUE THREAD

**Issue by Inside4ndroid** [SameerBidi/Torrent-Scraping#1]
Hi i am trying to run this on my server but i keep running into this error: 

Traceback (most recent call last):
  File "torrent_server.py", line 9, in <module>
    import TorrentScraper as scraper
  File "/var/www/html/tors/API/TorrentScraper.py", line 47
    source = get(f"http://1337x.unblockit.ltd/search/{search_key}/1/").text
    
    tried all sorts to fix it any help would be great :) Thank You!

**Comment by SameerBidi** [comment]
Its not clear whats wrong from the traceback you have provided
Can you share the full traceback? A screenshot will do

**Comment by Inside4ndroid** [comment]
this is all it gives me??

if i remove the f from get(f" then it says the next line with same get(f" is a syntax error too??

here is he cmd output

https://i4studio.co.uk/error.png

**Comment by Inside4ndroid** [comment]
think i found the problem lol....

i was using python torrent_server.py but its running the old 2.x version of python so i had to use python3 torrent_server.py

Sorry for waisting your time

**Comment by SameerBidi** [comment]
No problem, I was about to ask you the same thing

Although if you want to retain 2.x compatibility 

You can simply change those f" lines to this

source = get("http://1337x.unblockit.ltd/search/{}/1/".format(search_key)).text

**Comment by Inside4ndroid** [comment]
thanks for the info :)
 and thanks for your time :)
