### ISSUE TITLE
Site is no longer working

### ISSUE THREAD

**Issue by MMZaini** [SameerBidi/Torrent-Scraping#5]
This is what shows up when visiting the ["working demo"](http://samcloud.tplinkdns.com/torrent)

![image](https://user-images.githubusercontent.com/73606041/161856103-5fbdc337-91f0-4bbe-ab13-11d0b596f4ba.png)

**Comment by SameerBidi** [comment]
Thank you for reporting, fixed it yesterday but forgot to comment here.
